pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: BRIGHTSEC_API_KEY
    value: 0spnuda.nexa.c1goqd3vxnqxzangckjvwsjnyrizhglj
  - name: PROJECT_ID
    value: 4JtHcWih7ouZy7FBVUySo2
  - name: TARGET_URL
    value: https://brokencrystals.com/
  - name: NAME_DISCOVERY
    value: DiscoveryTest123
  - name: NAME_SCAN
    value: ScanTest123
  - name: PROJECT_NAME
    value: test_BC

stages:

  # ─── STAGE 1: Create Discovery ───────────────────────────────────
  - stage: CreateDiscovery
    displayName: 'Stage 1 - Create Discovery'
    jobs:
      - job: RunCreateDiscovery
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              pip install requests
              python3 create_discovery.py \
                --apiKey $(BRIGHTSEC_API_KEY) \
                --projectId $(PROJECT_ID) \
                --targetUrl $(TARGET_URL) \
                --nameDiscovery $(NAME_DISCOVERY)
            displayName: 'Create Discovery'

  # ─── STAGE 2: Wait for Discovery to Complete ─────────────────────
  - stage: WaitForDiscovery
    displayName: 'Stage 2 - Wait for Discovery'
    dependsOn: CreateDiscovery
    jobs:
      - job: WaitForDiscovery
        timeoutInMinutes: 60        # stop waiting after 60 min
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              pip install requests
              python3 wait_for_discovery.py \
                --api_key $(BRIGHTSEC_API_KEY) \
                --discovery_id $(DISCOVERY_ID)
            displayName: 'Wait for Discovery to Finish'

  # ─── STAGE 3: Run Scan ───────────────────────────────────────────
  - stage: RunScan
    displayName: 'Stage 3 - Run Scan'
    dependsOn: WaitForDiscovery
    jobs:
      - job: RunScan
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              pip install requests
              python3 run_ep_scan.py \
                --api_key $(BRIGHTSEC_API_KEY) \
                --scan_name $(NAME_SCAN) \
                --project_name $(PROJECT_NAME) \
                --project_id $(PROJECT_ID)
            displayName: 'Run Security Scan'
