trigger: none

pool:
  name: Default

variables:
  - name: PROJECT_ID
    value: rsGAc7oFBC4bPZiJAtrTo4
  - name: TARGET_URL
    value: https://brokencrystals.com/vendor/counter-up/jquery.waypoints.min.js
  - name: NAME_DISCOVERY
    value: DiscoveryTest123
  - name: NAME_SCAN
    value: ScanTest123
  - name: PROJECT_NAME
    value: Azure CI/CD Demo
  - name: DISCOVERY_ID
    value: qcSVG5QJaWKd8WkzESmDvR

stages:

  - stage: RunScan
    displayName: '3 - Run Security Scan'
    jobs:
      - job: RunScan
        steps:
          - script: pip3 install requests
            displayName: 'Install dependencies'
          - script: |
              echo "Discovery ID is: $(DISCOVERY_ID)"
              python3 run_ep_scan.py \
                --api_key $(BRIGHTSEC_API_KEY) \
                --scan_name $(NAME_SCAN) \
                --project_name "$(PROJECT_NAME)" \
                --project_id $(PROJECT_ID) \
                --discovery_id $(DISCOVERY_ID)
            displayName: 'Run Security Scan'
